### ISSUE TITLE
manifest screenshots

### ISSUE THREAD

**Issue by nstringham** [snake-pwa/snake-pwa.github.io#1]
I am making a gallery for web apps where each entry is automatically generated from an apps manifest. One of the things that can be added to the manifest is screenshots. Screenshots help users know what to expect from an app without needing to try it out. 

Additionally Chrome recently [announced their rich PWA install dialog](https://twitter.com/chromiumdev/status/1376472636058927104?lang=en) which will require screenshots to work

More information about screenshots is available in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots) and the [W3C spec](https://www.w3.org/TR/manifest-app-info/#screenshots-member).

If you want I can make a PR to add screenshots to snake-pwa

**Comment by snake-pwa** [comment]
Any contribution is welcome. If you open a PR with required changes I will be more than happy :)

If it's not a problem, can you create the PR in the repository [snake-pwa/snake](https://github.com/snake-pwa/snake)? Then I will move those changes here as well.

**Comment by snake-pwa** [comment]
Thanks, again :)
